config/routes.rb
BluewhaleSocialAdmin::Engine.routes.draw do

	root 'users#index'
	resources :dashboard
	resources :users do 
		get :change_password
		put :update_password
	end
	resources :posts do 
		get :assets
		get :video
	end
	resources :comments
 
end

app/controllers/bluewhale_social_admin/application_controller.rb
module BluewhaleSocialAdmin
	require 'csv'
  class ApplicationController < ActionController::Base
	before_filter :authenticate

      def as_csv(obj,cols)
        CSV.generate do |csv|
          csv << cols
          obj.each do |item|
            csv << item.attributes.values_at(*cols)
          end
        end
      end


 

	private
    def authenticate
      creds = YAML.load_file(Rails.root.to_s + '/config/admin.yml')
      authenticate_or_request_with_http_basic do |username, password|
        session[:admin] = true
        username ==  creds["username"] && password ==  creds["password"]
      end
    end

  end
end

app/controllers/bluewhale_social_admin/comments_controller.rb
require_dependency "bluewhale_social_admin/application_controller"

module BluewhaleSocialAdmin
  class CommentsController < ApplicationController

  	def index
  		params[:object_type] ||= "post"
  		search = params[:search].blank? ? ["1=1"] : ["lower(users.first_name) like :search or lower(users.last_name) like :search or lower(comments.comment) like :search or lower(users.username) = :search ",{:search => "#{params[:search].downcase}%"}]
  		sort = params[:sort].present? ? "#{params[:sort]} #{params[:dir]}" : "created_at desc"
  		search = ["object_type_id = ?",params[:object_type_id]]  if params[:object_type_id].present?
  		@comments = Comment.unscoped.joins(:user).where(search).where(["object_type = ?",params[:object_type]]).page(params[:page]).per(params[:per]).order(sort)
  	end

  	def edit
  		@comment = Comment.unscoped.find(params[:id])
  	end

	def update
		@comment = Comment.unscoped.find(params[:id])
		if @comment.update_attributes(comment_params)
			flash.now[:result] = "Comment updated"
		else
			flash.now[:error] = @comment.errors.full_messages
		end
		render :edit
	end


  	private
  	def comment_params
  		params.require(:comment).permit!
  	end

  end
end

app/controllers/bluewhale_social_admin/dashboard_controller.rb
require_dependency "bluewhale_social_admin/application_controller"

module BluewhaleSocialAdmin
  class DashboardController < ApplicationController

  	def index
  		  		
  	end
  end
end

app/controllers/bluewhale_social_admin/posts_controller.rb
require_dependency "bluewhale_social_admin/application_controller"

module BluewhaleSocialAdmin
  class PostsController < ApplicationController

	def index
		params[:search] ||= ""
		sort = params[:sort].present? ? "#{params[:sort]} #{params[:dir]}" : "created_at desc"
		search = params[:search].eql?("") ? ["1=1"] : ["lower(users.first_name) like :search or lower(users.last_name) like :search or lower(post_text) like :search or username = :search ",{:search => "#{params[:search].downcase}%"}]
		search = "users.id = #{params[:user_id]}" if params[:user_id].present?
		search = "posts.id = #{params[:post_id]}" if params[:post_id].present?
		@posts = Post.unscoped.where(search)
					.joins("left join (select count(*) comment_count,object_type_id from comments where object_type ='post' group by object_type_id) c on c.object_type_id = posts.id")
					.joins("left join (select count(*) like_count,object_type_id from likes where object_type ='post' group by object_type_id) l on l.object_type_id = posts.id")
					.joins(:user).page(params[:page]).per(params[:per]).order(sort)
	end

	def show
		@post = Post.unscoped.find(params[:id])
	end

	def edit
		@post = Post.unscoped.find(params[:id])
	end

	def update
		@post = Post.unscoped.find(params[:id])
		if @post.update_attributes(post_params)
			flash.now[:result] = "Post updated"
		else
			flash.now[:error] = @post.errors.full_messages
		end
		render :edit
	end

	def assets
		@asset =  Asset.find(params[:post_id]) 
	end

	def video
		@video = Asset.find(params[:post_id]) 
	end

	def destroy
		@post = Post.unscoped.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end


  	private
  	def post_params
  		params.require(:post).permit!
  	end

  end
end

app/controllers/bluewhale_social_admin/users_controller.rb
require_dependency "bluewhale_social_admin/application_controller"

module BluewhaleSocialAdmin
  class UsersController < ApplicationController

    def index
      params[:search] ||= ""
      sort = params[:sort].present? ? "#{params[:sort]} #{params[:dir]}" : "created_at desc"
      search = params[:search].eql?("") ? ["1=1"] : ["lower(users.first_name) like :search or lower(users.last_name) like :search or lower(username) = :search ", {:search => "#{params[:search].downcase}%"}]
      params[:page] ||= 1
      params[:per] ||= 25


      respond_to do |format|
        format.html {
          @users = User.unscoped.joins("left join (select count(*) post_count,user_id from posts group by user_id) p on p.user_id = users.id").where(search).order(sort).page(params[:page]).per(params[:per])
        }
        format.csv {
          @users = User.unscoped.where(search).order(sort)
          send_data self.as_csv(@users, ["username", "email", "facebook_id", "first_name", "last_name", "address1", "address2", "city", "state", "zip", "is_deleted"])
        }
      end

    end

    def new
      @user = User.new
    end

    def edit
      @user = User.unscoped.find(params[:id])
    end

    def create
      @user = User.new(user_params)
      if @user.save
        flash[:result] = "User created"
        redirect_to users_url
      else
        flash.now[:error] = @user.errors.full_messages
        render 'new'
      end
    end

    def update
      @user = User.unscoped.find(params[:id])
      if @user.update_attributes(user_params)
        @user.update_attribute("authentication_token", nil) if @user.is_deleted
        flash.now[:result] = "User updated"
      else
        flash.now[:error] = @user.errors.full_messages
      end
      render :edit
    end

    def destroy
      User.unscoped.find(params[:id]).destroy
      redirect_to users_path
    end

    def change_password
      @user = User.unscoped.find(params[:user_id])
    end

    def update_password
      @user = User.unscoped.find(params[:user_id])
      if @user.update_attributes(user_params)
        @user.pass_gen
        @user.save!(:validate => false)
        flash.now[:result] = "Password updated"
      else
        flash.now[:error] = @user.errors.full_messages
      end
      render :change_password
    end


    private
    def user_params
      params.require(:user).permit!
    end
  end
end

app/helpers/bluewhale_social_admin/application_helper.rb
module BluewhaleSocialAdmin
  module ApplicationHelper
  end
end

app/helpers/bluewhale_social_admin/comments_helper.rb
module BluewhaleSocialAdmin
  module CommentsHelper
  end
end

app/helpers/bluewhale_social_admin/dashboard_helper.rb
module BluewhaleSocialAdmin
  module DashboardHelper
  end
end

app/helpers/bluewhale_social_admin/posts_helper.rb
module BluewhaleSocialAdmin
  module PostsHelper
  end
end

app/helpers/bluewhale_social_admin/users_helper.rb
module BluewhaleSocialAdmin
  module UsersHelper
  end
end

app/views/bluewhale_social_admin/comments/edit.html.erb
<h4>Edit Comment: <%= @comment.id %></h4>
<%= form_for :comment, :url => comment_path(@comment), :html => {:id => "edit-form",:class => "form-horizontal" , :method => :put} do |f| %>

<% if flash[:error].present? %>
<div class="alert alert-error">
	<%= flash[:error].join("<br>").html_safe %>
</div>
<% end %>

<% if flash[:result].present? %>
<div class="alert alert-success">
	<%= flash[:result] %>
</div>
<% end %>
  <div class="control-group"> 
    <%= f.label :name, :class =>"control-label" %>
    <div class="controls">
      <%= @comment.user.first_name %> <%= @comment.user.last_name %>
    </div>
  </div>
  <div class="control-group"> 
    <%= f.label :comment, :class =>"control-label" %>
    <div class="controls">
      <%= f.text_area :comment %>
    </div>
  </div>
 
  <div class="control-group">  
    <div class="controls">
      <%= f.check_box :deleted %> Blocked
    </div>
  </div>
 

  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn save-btn">Save</button>
       <a href="<%= comments_path %>" class="btn">Cancel</a>
    </div>
  </div>
<% end %>

app/views/bluewhale_social_admin/comments/index.html.erb
<h4>Comments</h4>
<%= form_tag comments_path,:method => :get,:id => "list-form" do |f| %>
<input type="hidden" name="sort" id="sort" value="<%= params[:sort] if params[:sort].present? %>">
<div class="input-append">
 
  <%= text_field_tag :search,params[:search], :class => "span2", :id =>  "appendedInputButton" %>
  <button class="btn">Search</button>  
 
</div>
<% end %>
<div id="post-media" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<table class="table">
	<tr>
		<th></th>
		<th>id</th>
	 	<th>post id</th>
		<th><a href="#" class="sortable" data-sort="users.first_name">posted by</a></th>
  
		<th><a href="#" class="sortable" data-sort="post_text">comment</a></th>
 
		<th><a href="#" class="sortable" data-sort="posts.is_deleted">status</a></th>
		<th><a href="#" class="sortable" data-sort="posts.created_at">created</a></th>
	</tr>
	<% @comments.each do |u| %>
	<tr>
		<td> 
			<a href="<%= edit_comment_path(u) %>"><i class="icon-pencil" title="Edit"></i></a>&nbsp;
			<%= link_to '<i class="icon-trash" title="Delete"></i>'.html_safe, post_path(u), :method => :delete, :confirm => "Are you sure you want to delete this post, this can not be un-done?" %>
			
		</td>
		<td><%= u.id %></td>
	 	<td><a href="<%= posts_path(:post_id => u.object_type_id)  %>"><%= u.object_type_id %></a></td>
		<td><a href="<%= edit_user_path(u.user) %>"><%= u.user.first_name %> <%= u.user.last_name %></a></td>
		<td><%= u.comment %></td>
 
 
 
		<td><%= !u.deleted ? "Active" : "Hidden" %></td>
		<td><%= u.created_at.strftime("%m/%d/%Y %I:%M:%S") %></td>

	</tr>
	<% end %>

</table>
<%= paginate(@comments) %>

app/views/bluewhale_social_admin/dashboard/index.html.erb
<h4>Dashboard</h4>

app/views/bluewhale_social_admin/posts/_media.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Assets <%= @asset.id %></h3>
  </div>
  <div class="modal-body">
    <p>
 <img src="<%= @asset.file(:large) %>" width="250">  
 

    </p>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
   
  </div>
 

app/views/bluewhale_social_admin/posts/_video_player.html.erb
<script type="text/javascript">
    $(document).ready(function(){
      $(".video-stop").click(function(){
        $("#video_player").each(function () { this.pause() });
      });
    });

</script>
  <div class="modal-header">
    <button type="button" class="close video-stop" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Video <%= @video.id %></h3>
  </div>
  <div class="modal-body">
    <p>
    <video id="video_player" src="<%= @video.file(:original) %>" style="width:320px;height:240px;" controls></video>

    </p>
  </div>
  <div class="modal-footer">
    <button class="btn video-stop" data-dismiss="modal" aria-hidden="true">Close</button>
   
  </div>

app/views/bluewhale_social_admin/posts/assets.js.erb
$("#post-media").html("<%= j render :partial => 'media' %>").modal('show');

app/views/bluewhale_social_admin/posts/edit.html.erb
<h4>Edit Post: <%= @post.id %></h4>
<%= form_for :post, :url => post_path(@post), :html => {:id => "edit-form",:class => "form-horizontal" , :method => :put} do |f| %>

<% if flash[:error].present? %>
<div class="alert alert-error">
	<%= flash[:error].join("<br>").html_safe %>
</div>
<% end %>

<% if flash[:result].present? %>
<div class="alert alert-success">
	<%= flash[:result] %>
</div>
<% end %>
  <div class="control-group"> 
    <%= f.label :name, :class =>"control-label" %>
    <div class="controls">
      <%= @post.user.first_name %> <%= @post.user.last_name %>
    </div>
  </div>
  <div class="control-group"> 
    <%= f.label :post_text, :class =>"control-label" %>
    <div class="controls">
      <%= f.text_area :post_text %>
    </div>
  </div>
  <div class="control-group"> 
    <%= f.label :assets, :class =>"control-label" %>
    <div class="controls">
    <% @post.assets.each do |a| %>
      <%= image_tag(a.file(:thumb),:style => "height:70px;")  %> &nbsp;
    <% end %>
    </div>
  </div>
 
  <div class="control-group">  
    <div class="controls">
      <%= f.check_box :is_deleted %> Blocked
    </div>
  </div>
 

  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn save-btn">Save</button>
       <a href="<%= posts_path %>" class="btn">Cancel</a>
    </div>
  </div>
<% end %>

app/views/bluewhale_social_admin/posts/index.html.erb
<h4>Posts</h4>
<%= form_tag posts_path,:method => :get,:id => "list-form" do |f| %>
<input type="hidden" name="sort" id="sort" value="<%= params[:sort] if params[:sort].present? %>">
<div class="input-append">
 
  <%= text_field_tag :search,params[:search], :class => "span2", :id =>  "appendedInputButton" %>
  <button class="btn">Search</button>  
 
</div>
<% end %>
<div id="post-media" class="modal hide" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
<table class="table">
	<tr>
		<th></th>
		<th>id</th>
	 	<th>parent post</th>
		<th><a href="#" class="sortable" data-sort="users.first_name">posted by</a></th>
		<th><a href="#" class="sortable" data-sort="like_count">likes</a></th>
		<th><a href="#" class="sortable" data-sort="comment_count">comments</a></th>
		<th><a href="#" class="sortable" data-sort="post_text">post_text</a></th>
		<th>assets</th>
		<th><a href="#" class="sortable" data-sort="flag">flags</a></th>
		<th><a href="#" class="sortable" data-sort="posts.is_deleted">status</a></th>
		<th><a href="#" class="sortable" data-sort="posts.created_at">created</a></th>
	</tr>
	<% @posts.each do |u| %>
	<% warning = u.flag.present? ? u.flag : 0 %>
	<tr<%= " class='error'".html_safe if !warning.eql?(0) %>>
		<td> 
			<a href="<%= edit_post_path(u) %>"><i class="icon-pencil" title="Edit"></i></a>&nbsp;
			<%= link_to '<i class="icon-trash" title="Delete"></i>'.html_safe, post_path(u), :method => :delete, :confirm => "Are you sure you want to delete this post, this can not be un-done?" %>
			
		</td>
		<td><%= u.id %></td>
	 	<td><a href="?post_id=<%= u.parent_post_id  %>"><%= u.parent_post_id %></a></td>
		<td><a href="<%= edit_user_path(u.user) %>"><%= u.user.first_name %> <%= u.user.last_name %></a></td>
		<td><%= u.likes.count %></td>
		<td><a href="<%= comments_path(:object_type_id => u.id,:object_type => 'post') %>"><%= u.comments.count %></a></td>
		<td><%= u.post_text %></td>
 
		<td>
		<% u.assets.each do |a| %>
			<% if a.file_content_type.include?("image/") %>
				<%= link_to image_tag(a.file(:thumb),:style => "height:40px;") , post_assets_path(a), :remote => true,"data-toggle" => "modal" %>  
			<% else %>
				<%= link_to image_tag("video.png",:style => "height:40px;") , post_video_path(a), :remote => true,"data-toggle" => "modal" %> 
			<% end %>&nbsp;
		<% end %>
		</td>
		<td><%= u.flag %></td>
		<td><%= !u.is_deleted ? "Active" : "Hidden" %></td>
		<td><%= u.created_at.strftime("%m/%d/%Y %I:%M:%S") %></td>

	</tr>
	<% end %>

</table>
<%= paginate(@posts) %>

app/views/bluewhale_social_admin/posts/video.js.erb
$("#post-media").html("<%= j render :partial => 'video_player' %>").modal('show');

app/views/bluewhale_social_admin/users/change_password.html.erb
<h4>Change Password: <%= @user.first_name %> <%= @user.last_name %></h4>

<%= form_for :user, :url => user_update_password_path(@user), :html => {:id => "edit-form",:class => "form-horizontal" , :method => :put} do |f| %>
<% if flash[:error].present? %>
<div class="alert alert-error">
  <%= flash[:error].join("<br>").html_safe %>
</div>
<% end %>

<% if flash[:result].present? %>
<div class="alert alert-success">
  <%= flash[:result] %>
</div>
<% end %>
   <div class="control-group"> 
    <%= f.label :password, :class =>"control-label" %>
    <div class="controls">
      <%= f.password_field :password %>
    </div>
  </div>
    <div class="control-group"> 
    <%= f.label :password_confirmation, :class =>"control-label" %>
    <div class="controls">
      <%= f.password_field :password_confirmation %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn save-btn">Save</button>
       <a href="<%= edit_user_path(@user) %>" class="btn">Cancel</a>
    </div>
  </div>
<% end %>

app/views/bluewhale_social_admin/users/edit.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$(".save-btn").click(function(e){
			e.preventDefault();
			if($("#user_is_deleted").is(":checked")) {
				if (confirm("Are you sure you want to block this user? User will be logged out and all posts will become hidden.") ) {
					$("#edit-form").submit();
				}
			} else {
				$("#edit-form").submit();
			}
		});
	});

</script>
<h4>Edit User: <%= @user.first_name %> <%= @user.last_name %></h4>
<%= form_for :user, :url => user_path(@user), :html => {:id => "edit-form",:class => "form-horizontal" , :method => :put} do |f| %>

<% if flash[:error].present? %>
<div class="alert alert-error">
	<%= flash[:error].join("<br>").html_safe %>
</div>
<% end %>

<% if flash[:result].present? %>
<div class="alert alert-success">
	<%= flash[:result] %>
</div>
<% end %>
  <div class="control-group"> 
    <%= f.label :first_name, :class =>"control-label" %>
    <div class="controls">
      <%= f.text_field :first_name %>
    </div>
  </div>
  <div class="control-group"> 
    <%= f.label :last_name, :class =>"control-label" %>
    <div class="controls">
      <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="control-group"> 
    <%= f.label :username, :class =>"control-label" %>
    <div class="controls">
      <%= f.text_field :username %>
    </div>
  </div>
  <div class="control-group"> 
    <%= f.label :email, :class =>"control-label" %>
    <div class="controls">
      <%= f.text_field :email %>
    </div>
  </div>
   <div class="control-group"> 
    <%= f.label :password, :class =>"control-label" %>
    <div class="controls">
      <%= link_to "Change Password", user_change_password_path(@user) %>
    </div>
  </div>
  
 
  <div class="control-group">  
    <div class="controls">
      <%= f.check_box :is_deleted %> Blocked
    </div>
  </div>
 

  <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn save-btn">Save</button>
       <a href="<%= users_path %>" class="btn">Cancel</a>
    </div>
  </div>
<% end %>

app/views/bluewhale_social_admin/users/index.html.erb
<%= button_to 'Add', new_user_path, method: :get,  class: 'btn btn-success pull-right', style: 'margin-bottom: 10px;' %>
<h4>Users</h4>
<%= form_tag users_path,:method => :get ,:id => "list-form" do |f| %>
<input type="hidden" name="sort" id="sort" value="<%= params[:sort] if params[:sort].present? %>">	
<div class="input-append">
 
  <%= text_field_tag :search,params[:search], :class => "span2", :id =>  "appendedInputButton" %>
  <button class="btn html">Search</button>  <a href="#" class="btn csv">Download Results</a>  
<br><br>
 
</div>
<% end %>
Results: <%= @users.total_count %><br>
<br>

<table class="table">
	<tr>
		<th></th>
		<th>id</th>
		<th></th>
		<th><a href="#" class="sortable" data-sort="post_count">posts</a></th>
		<th><a href="#" class="sortable" data-sort="users.first_name">name</a></th>
		<th><a href="#" class="sortable" data-sort="users.email">email</a></th>
		<th><a href="#" class="sortable" data-sort="users.is_deleted">status</a></th> 
		<th><a href="#" class="sortable" data-sort="users.created_at">created</a></th>
	</tr>
	<% @users.each do |u| %>
	<tr>
		<td><a href="<%= edit_user_path(u) %>"><i class="icon-pencil" title="Edit"></i></a>&nbsp;
<%= link_to '<i class="icon-trash" title="Delete"></i>'.html_safe,user_path(u), :method => :delete, :confirm => "Are you sure you want to delete this user? This cannot be un-done." %>
		</td>
		<td><%= u.id %></td>
		<th><%= image_tag u.avatar(:avatar_small) ,:style => "height:30px" %></th>
		<td><a href="/admin/posts?user_id=<%= u.id %>"><%= u.posts.count %></a></td>
		<td><%= u.first_name %> <%= u.last_name %></td>
		<td><%= u.email %></td>
		<td><%= !u.is_deleted ? "Active" : "Blocked" %></td>
 
		<td><%= u.created_at.strftime("%m/%d/%Y %I:%M:%S") %></td>

	</tr>
	<% end %>

</table>
 <%= paginate @users %>

 <script type="text/javascript">
	$(".btn.csv").click(function(e){
		e.preventDefault();
		act = $("#list-form").attr("action");
		if (act.indexOf(".csv") > -1) {
			$("#list-form").attr("action",$("#list-form").attr("action"));
		} else {
			$("#list-form").attr("action",$("#list-form").attr("action")+".csv");
		}
		
		$("#list-form").submit();
	});
	$(".btn.html").click(function(e){
		e.preventDefault();
		$("#list-form").attr("action","<%= users_path %>");
		$("#list-form").submit();
	});
 </script>

app/views/bluewhale_social_admin/users/new.html.erb
<h4>Create User: </h4>
<%= form_for @user, :html => {:id => "edit-form", :class => "form-horizontal", :method => :post} do |f| %>
    <% if flash[:error].present? %>
        <div class="alert alert-error">
          <%= flash[:error].join("<br>").html_safe %>
        </div>
    <% end %>

    <% if flash[:result].present? %>
        <div class="alert alert-success">
          <%= flash[:result] %>
        </div>
    <% end %>
    <div class="control-group">
      <%= f.label :first_name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :first_name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :last_name, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :last_name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :username, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :username %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password, :class => "control-label" %>
      <div class="controls">
        <%= f.password_field :password %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :password_confirmation, :class => "control-label" %>
      <div class="controls">
        <%= f.password_field :password_confirmation %>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn save-btn">Save</button>
        <a href="<%= users_path %>" class="btn">Cancel</a>
      </div>
    </div>
<% end %>

app/views/layouts/bluewhale_social_admin/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= Rails.application.class.parent_name %> Admin</title>
  <%= stylesheet_link_tag    "bluewhale_social_admin/application", media: "all" %>
  <%= javascript_include_tag "bluewhale_social_admin/application" %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
  <body>

     <div class="container">

      <div class="masthead">
        <h3 class="muted"><%= Rails.application.class.parent_name %> Admin</h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <% if params[:controller].eql?("users") %><li class='active'><% else %><li><% end %><a href="<%= users_path %>">Users</a></li>
                <% if params[:controller].eql?("posts") %><li class='active'><% else %><li><% end %><a href="<%= posts_path %>">Posts</a></li>
                <% if params[:controller].eql?("comments") %><li class='active'><% else %><li><% end %><a href="<%= comments_path(:object_type => 'post') %>">Post Comments</a></li>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>
		<%= yield %>
</div>

</body>
</html>